export interface CityGroup {
  label: string;
  alternatives: string[];
}

export const CITIES: CityGroup[] = [
  { label: "Adelaide", alternatives: ["Adelaide"] },
  { label: "Asheville", alternatives: ["Asheville"] },
  { label: "Atlanta", alternatives: ["Atlanta", "Lawrenceville"] },
  { label: "Austin", alternatives: ["Austin"] },
  { label: "Barcelona", alternatives: ["Barcelona"] },
  { label: "Boston", alternatives: ["Boston"] },
  { label: "Brisbane", alternatives: ["Brisbane", "Gold Coast", "Sunshine Coast"] },
  { label: "Buenos Aires", alternatives: ["Buenos Aires"] },
  { label: "Cape Town", alternatives: ["Cape Town"] },
  { label: "Charleston", alternatives: ["Charleston"] },
  { label: "Charlotte", alternatives: ["Charlotte", "Davidson"] },
  { label: "Chicago", alternatives: ["Chicago"] },
  { label: "Cincinnati", alternatives: ["Cincinnati"] },
  { label: "Cleveland", alternatives: ["Cleveland"] },
  { label: "Columbus", alternatives: ["Columbus"] },
  { label: "Dallas", alternatives: ["Dallas", "Dallas Metro", "Forth Worth"] },
  { label: "Denver", alternatives: ["Denver", "Front Range", "Boulder", "Arvada", "arvada", "Littleton", "Parker", "Colorado Springs"] },
  { label: "Detroit", alternatives: ["Detroit"] },
  { label: "Doha", alternatives: ["Doha"] },
  { label: "Dubai", alternatives: ["Dubai"] },
  { label: "Dublin", alternatives: ["Dublin"] },
  { label: "Edinburgh", alternatives: ["Edinburgh"] },
  { label: "Houston", alternatives: ["Houston"] },
  { label: "Indianapolis", alternatives: ["Indianapolis"] },
  { label: "Jacksonville", alternatives: ["Jacksonville", "Orange Park", "Ponte Vedra Beach"] },
  { label: "Kansas City", alternatives: ["Kansas City"] },
  { label: "Kuala Lumpur", alternatives: ["Kuala Lumpur"] },
  { label: "Las Vegas", alternatives: ["Las Vegas", "Las Vegas Metro", "Boulder City"] },
  { label: "Lisbon", alternatives: ["Lisbon"] },
  { label: "London", alternatives: ["Greater London", "St Albans", "Maidstone", "London", "Windsor", "Chelsea"] },
  { label: "Los Angeles", alternatives: ["Los Ángeles", "Pasadena", "Santa Barbara", "Los Angeles", "San Luis Obispo", "Lancaster", "LA"] },
  { label: "Madison", alternatives: ["Madison"] },
  { label: "Melbourne", alternatives: ["Melbourne"] },
  { label: "Memphis", alternatives: ["Memphis"] },
  { label: "Mexico City", alternatives: ["Mexico City"] },
  { label: "Miami", alternatives: ["Miami", "Miami Metro", "Miami Beach", "Fort Lauderdale", "Boca Raton", "Delray Beach", "Palm Beach"] },
  { label: "Minneapolis", alternatives: ["Minneapolis"] },
  { label: "Montreal", alternatives: ["Montreal", "Montréal"] },
  { label: "Nashville", alternatives: ["Nashville"] },
  { label: "New York", alternatives: ["NYC", "NY", "New York City", "New York"] },
  { label: "Orange County", alternatives: ["Orange County", "Coastal SoCal", "Newport Beach", "Huntington Beach", "Seal Beach"] },
  { label: "Orlando", alternatives: ["Orlando"] },
  { label: "Palm Springs", alternatives: ["Palm Springs"] },
  { label: "Paris", alternatives: ["Paris"] },
  { label: "Perth", alternatives: ["Perth"] },
  { label: "Philadelphia", alternatives: ["Philadelphia"] },
  { label: "Phoenix", alternatives: ["Phoenix", "Phoenix Metro", "Scottsdale", "Gilbert"] },
  { label: "Pittsburgh", alternatives: ["Pittsburgh"] },
  { label: "Portland", alternatives: ["Portland", "Camas"] },
  { label: "Raleigh", alternatives: ["Raleigh"] },
  { label: "Richmond", alternatives: ["Richmond"] },
  { label: "Sacramento", alternatives: ["Sacramento"] },
  { label: "Salt Lake City", alternatives: ["Salt Lake City"] },
  { label: "San Antonio", alternatives: ["San Antonio"] },
  { label: "San Diego", alternatives: ["San Diego Metro", "Encinitas", "Escondido", "San Diego", "Temecula Valley"] },
  { label: "San Francisco", alternatives: ["San Francisco", "San Francisco Bay Area", "Palo Alto", "Sausalito", "San Rafael"] },
  { label: "Sao Paulo", alternatives: ["Sao Paulo", "São Paulo", "Sao Paolo", "São Paolo", "Sao Paul"] },
  { label: "Seattle", alternatives: ["Seattle", "Issaquah"] },
  { label: "Singapore", alternatives: ["Singapore"] },
  { label: "Spokane", alternatives: ["Spokane"] },
  { label: "St Louis", alternatives: ["St Louis", "St. Louis"] },
  { label: "Sydney", alternatives: ["Sydney"] },
  { label: "Tampa", alternatives: ["Tampa", "Tampa Bay", "St Petersburg", "Sarasota"] },
  { label: "Toronto", alternatives: ["Toronto"] },
  { label: "Tucson", alternatives: ["Tucson"] },
  { label: "Vancouver", alternatives: ["Vancouver", "Surrey/Vancouver"] },
  { label: "Washington DC", alternatives: ["Washington", "Washington DC", "Washington DC Metro", "McLean VA"] },
];
