/**
 * Explicit city → IANA timezone map for the introduction scheduler.
 *
 * Used to rewrite each city's schedule so it runs at a local wall-clock
 * time in the city's own timezone (day 1, 10:00 local). Kept as an explicit
 * table (not Airtable-derived) because member/city timezone data in Airtable
 * is sparse and country-level defaults are too coarse for multi-zone
 * countries (US/Canada/Australia).
 */

export const CITY_TIMEZONES: Record<string, string> = {
  // ── United States ──────────────────────────────────────────────
  // East
  Akron: "America/New_York",
  Algonac: "America/New_York",
  Asheville: "America/New_York",
  Atlanta: "America/New_York",
  "Boca Raton": "America/New_York",
  Boston: "America/New_York",
  "Boynton Beach": "America/New_York",
  Brooklyn: "America/New_York",
  Charleston: "America/New_York",
  Charlotte: "America/New_York",
  Cincinnati: "America/New_York",
  Cleveland: "America/New_York",
  Columbus: "America/New_York",
  Davidson: "America/New_York",
  "Delray Beach": "America/New_York",
  Detroit: "America/New_York",
  Devon: "America/New_York",
  Doylestown: "America/New_York",
  Elizabeth: "America/New_York",
  Fairfax: "America/New_York",
  "Fort Lauderdale": "America/New_York",
  "Glen Allen": "America/New_York",
  Hudson: "America/New_York",
  Indianapolis: "America/New_York",
  Jacksonville: "America/New_York",
  Lancaster: "America/New_York",
  "Lauderdale-by-the-Sea": "America/New_York",
  Lawrenceville: "America/New_York",
  "Long Island": "America/New_York",
  Louisville: "America/New_York",
  "McLean VA": "America/New_York",
  Miami: "America/New_York",
  "Miami Beach": "America/New_York",
  "New York": "America/New_York",
  "Orange Park": "America/New_York",
  Orlando: "America/New_York",
  "Palm Beach": "America/New_York",
  "Palm Beach Gardens": "America/New_York",
  Philadelphia: "America/New_York",
  Pittsburgh: "America/New_York",
  "Ponte Vedra Beach": "America/New_York",
  Pulaski: "America/New_York",
  Raleigh: "America/New_York",
  Richmond: "America/New_York",
  Sarasota: "America/New_York",
  Savannah: "America/New_York",
  "St. Petersburg": "America/New_York",
  Summerville: "America/New_York",
  Tampa: "America/New_York",
  "Washington, D.C.": "America/New_York",
  "Westminster, VA": "America/New_York",
  Burlington: "America/New_York",
  // Central
  Austin: "America/Chicago",
  "Blue Springs": "America/Chicago",
  Chicago: "America/Chicago",
  Dallas: "America/Chicago",
  Euless: "America/Chicago",
  "Fort Worth": "America/Chicago",
  Houston: "America/Chicago",
  "Kansas City": "America/Chicago",
  Madison: "America/Chicago",
  McAllen: "America/Chicago",
  Memphis: "America/Chicago",
  Minneapolis: "America/Chicago",
  Nashville: "America/Chicago",
  "San Antonio": "America/Chicago",
  "St. Louis": "America/Chicago",
  Waco: "America/Chicago",
  // Mountain
  Arvada: "America/Denver",
  Boulder: "America/Denver",
  "Colorado Springs": "America/Denver",
  Denver: "America/Denver",
  Littleton: "America/Denver",
  Parker: "America/Denver",
  "Salt Lake City": "America/Denver",
  // Arizona (no DST)
  Gilbert: "America/Phoenix",
  Phoenix: "America/Phoenix",
  Scottsdale: "America/Phoenix",
  Tucson: "America/Phoenix",
  // West
  Berkeley: "America/Los_Angeles",
  "Boulder City": "America/Los_Angeles",
  Camas: "America/Los_Angeles",
  Carlsbad: "America/Los_Angeles",
  Encinitas: "America/Los_Angeles",
  Escondido: "America/Los_Angeles",
  Henderson: "America/Los_Angeles",
  "Huntington Beach": "America/Los_Angeles",
  Issaquah: "America/Los_Angeles",
  "Laguna Beach": "America/Los_Angeles",
  "Las Vegas": "America/Los_Angeles",
  "Los Angeles": "America/Los_Angeles",
  "Los Gatos": "America/Los_Angeles",
  "Menlo Park": "America/Los_Angeles",
  "Newport Beach": "America/Los_Angeles",
  Oakland: "America/Los_Angeles",
  Oceanside: "America/Los_Angeles",
  "Orange County": "America/Los_Angeles",
  "Palm Springs": "America/Los_Angeles",
  "Palo Alto": "America/Los_Angeles",
  Pasadena: "America/Los_Angeles",
  Portland: "America/Los_Angeles",
  "Redondo Beach": "America/Los_Angeles",
  Sacramento: "America/Los_Angeles",
  "San Diego": "America/Los_Angeles",
  "San Francisco": "America/Los_Angeles",
  "San Luis Obispo": "America/Los_Angeles",
  "San Rafael": "America/Los_Angeles",
  "Santa Barbara": "America/Los_Angeles",
  "Seal Beach": "America/Los_Angeles",
  Seattle: "America/Los_Angeles",
  Spokane: "America/Los_Angeles",
  Sunnyvale: "America/Los_Angeles",
  "Temecula Valley": "America/Los_Angeles",
  Vacaville: "America/Los_Angeles",
  "Woodland Hills": "America/Los_Angeles",
  // Alaska / Hawaii
  Juneau: "America/Juneau",
  Honolulu: "Pacific/Honolulu",

  // ── Canada ──────────────────────────────────────────────────────
  "Burlington, Ontario": "America/Toronto",
  Burnaby: "America/Vancouver",
  Etobicoke: "America/Toronto",
  Mississauga: "America/Toronto",
  Montréal: "America/Toronto",
  Oakville: "America/Toronto",
  "Richmond Hill": "America/Toronto",
  Surrey: "America/Vancouver",
  "Surrey/Vancouver": "America/Vancouver",
  Toronto: "America/Toronto",
  Vancouver: "America/Vancouver",
  Whitby: "America/Toronto",
  Windsor: "America/Toronto",

  // ── UK / Ireland ────────────────────────────────────────────────
  Chelsea: "Europe/London",
  Drogheda: "Europe/Dublin",
  Dublin: "Europe/Dublin",
  Edinburgh: "Europe/London",
  London: "Europe/London",
  Maidstone: "Europe/London",
  "St Albans": "Europe/London",
  "Windsor, UK": "Europe/London",

  // ── Europe ──────────────────────────────────────────────────────
  Barcelona: "Europe/Madrid",
  Berlin: "Europe/Berlin",
  Florence: "Europe/Rome",
  Lisbon: "Europe/Lisbon",
  Nuremberg: "Europe/Berlin",
  Paris: "Europe/Paris",
  València: "Europe/Madrid",
  Venice: "Europe/Rome",

  // ── Africa / Middle East / Asia ─────────────────────────────────
  "Abu Dhabi": "Asia/Dubai",
  Bangalore: "Asia/Kolkata",
  "Cape Town": "Africa/Johannesburg",
  "Da Nang": "Asia/Ho_Chi_Minh",
  Doha: "Asia/Qatar",
  Dubai: "Asia/Dubai",
  "Kuala Lumpur": "Asia/Kuala_Lumpur",
  Lagos: "Africa/Lagos",
  "Phu Quoc": "Asia/Ho_Chi_Minh",
  Singapore: "Asia/Singapore",
  Stellenbosch: "Africa/Johannesburg",
  Tokyo: "Asia/Tokyo",
  Virtual: "UTC",

  // ── Latin America ───────────────────────────────────────────────
  "Buenos Aires": "America/Argentina/Buenos_Aires",
  "São Paulo": "America/Sao_Paulo",
  "Mexico City": "America/Mexico_City",

  // ── Australia ───────────────────────────────────────────────────
  Adelaide: "Australia/Adelaide",
  "Bellevue Hill": "Australia/Sydney",
  Brisbane: "Australia/Brisbane",
  "Byron Bay": "Australia/Sydney",
  Cairns: "Australia/Brisbane",
  "Gold Coast": "Australia/Brisbane",
  Hobart: "Australia/Hobart",
  "Hope Island": "Australia/Brisbane",
  "Lane Cove": "Australia/Sydney",
  Melbourne: "Australia/Melbourne",
  Perth: "Australia/Perth",
  Robina: "Australia/Brisbane",
  "Sunshine Coast": "Australia/Brisbane",
  Sydney: "Australia/Sydney",
  Uki: "Australia/Sydney",
};
